#!/usr/bin/env node

// Generates TOP200.md (the star leaderboard) from data/repositories.json and
// data/curated.json. The snapshot is refreshed daily by the update-catalog
// workflow, which runs this script right after scripts/update.mjs, so the
// leaderboard stays in sync with the catalog.
//
// The old TOP100.md was hand-maintained; the board is now generated from the
// snapshot so it can follow daily star changes. Editorial exclusions (topic
// riders, blacklisted repositories) still apply through data/curated.json, and
// the generated page is reviewed by humans periodically.
//
// To shrink the board back to Top 100 later: run with TOP_N=100 (or change the
// default below), rename TOP200.md to TOP100.md, and update the links in
// README.md, README_EN.md, and the CATALOG header inside scripts/update.mjs.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOP_N = Number(process.env.TOP_N ?? 200);
const OUTPUT = 'TOP200.md';

const snapshot = JSON.parse(await readFile(resolve(root, 'data/repositories.json'), 'utf8'));
const curated = JSON.parse(await readFile(resolve(root, 'data/curated.json'), 'utf8'));
const excludedRepos = new Map(
  Object.entries(curated.excluded_repos || {}).map(([fullName, reason]) => [fullName.toLowerCase(), reason]),
);
// Repositories kept in the catalog but kept out of the star board — e.g. a
// generic multi-agent product whose stars do not reflect DSH usage, although
// it ships a DSH plugin somewhere inside. Purely editorial, like the old
// hand-maintained TOP100.md head.
const leaderboardExclusions = new Map(
  Object.entries(curated.leaderboard_exclusions || {}).map(([fullName, reason]) => [fullName.toLowerCase(), reason]),
);

const date = snapshot.fetched_at.slice(0, 10);
const repositories = snapshot.repositories
  .filter((repo) => repo.description && repo.description.trim())
  .filter((repo) => !excludedRepos.has(repo.full_name.toLowerCase()))
  .filter((repo) => !leaderboardExclusions.has(repo.full_name.toLowerCase()))
  .sort((a, b) => b.stargazers_count - a.stargazers_count || a.full_name.localeCompare(b.full_name));
// Only excluded repositories that would otherwise be listed (description set)
// count here — mirrors the "excluded N" headline in CATALOG.md.
const excludedCount = snapshot.repositories.filter(
  (repo) => repo.description && repo.description.trim() && excludedRepos.has(repo.full_name.toLowerCase()),
).length;
const boardExcludedCount = snapshot.repositories.filter(
  (repo) =>
    repo.description &&
    repo.description.trim() &&
    !excludedRepos.has(repo.full_name.toLowerCase()) &&
    leaderboardExclusions.has(repo.full_name.toLowerCase()),
).length;

const top = repositories.slice(0, TOP_N);
const esc = (value) => String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');
const updated = (repo) => repo.updated_at.slice(0, 10);
const rows = top.map(
  (repo, index) =>
    `| ${index + 1} | [${repo.full_name}](${repo.html_url}) | ${esc(repo.description || '—')} | ${repo.language || '—'} | ${repo.stargazers_count} | ${repo.license || '—'} | ${updated(repo)} |`,
);

const page = `# DSH 插件 Star 排行榜 Top ${TOP_N} / Top ${TOP_N} DSH Plugins by Stars

[返回中文首页](./README.md) · [Back to English home](./README_EN.md) · [完整目录 / Full catalog](./CATALOG.md) · [作者自荐 / Author showcase](./SHOWCASE.md) · [JSON data](./data/repositories.json)

按 Star 数排序的前 ${TOP_N} 个 DSH 插件仓库，由 \`scripts/top.mjs\` 从 [data/repositories.json](./data/repositories.json) 快照自动生成，并随每日目录刷新同步更新。带有 \`dsh-plugin\` Topic 但并非 DSH 插件的仓库（平台本体、其他 Agent 工具、同名目录站等）以及编辑部拉黑的仓库已剔除；少数星数主要来自通用产品、并非 DSH 生态真实热度的仓库不参与榜单排序（仍保留在全量目录中），两处清单与理由分别记录在 [data/curated.json](./data/curated.json) 的 \`excluded_repos\` 与 \`leaderboard_exclusions\`。编辑部会定期人工复核头部条目。排名反映受欢迎程度，不代表安全性、兼容性或质量背书。

The top ${TOP_N} DSH plugin repositories ranked by GitHub stars, generated by \`scripts/top.mjs\` from the [data/repositories.json](./data/repositories.json) snapshot and refreshed together with the daily catalog. Repositories that carry the \`dsh-plugin\` topic without being DSH plugins (the platform itself, other agent tools, competing catalogs) and editorially blacklisted repositories are excluded; a few repositories whose stars come mainly from a generic product rather than real DSH-ecosystem popularity are kept in the catalog but left out of this ranking. Both lists and their reasons live in [data/curated.json](./data/curated.json) under \`excluded_repos\` and \`leaderboard_exclusions\`. The editorial team periodically reviews the head of the ranking by hand. Ranking reflects popularity only — it is not a claim of security, compatibility, or quality.

- 快照日期 / Snapshot date: **${date} (UTC)**
- 收录条目 / Entries: **${top.length}**
- 已剔除仓库 / Excluded repositories: **${excludedCount}**
- 不参与榜单 / Kept out of the board: **${boardExcludedCount}**

| # | Project | Description | Language | Stars | License | Updated |
| ---: | --- | --- | --- | ---: | --- | --- |
${rows.join('\n')}

## Data source

Generated by \`node scripts/top.mjs\` (set \`TOP_N=100\` to regenerate as a Top 100 board). Complete metadata is available in [data/repositories.json](./data/repositories.json).
`;

await writeFile(resolve(root, OUTPUT), page);
console.log(
  `Generated ${OUTPUT} with ${top.length} repositories (snapshot ${date}, excluded ${excludedCount}, kept out of the board ${boardExcludedCount}).`,
);
